/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualFormularios;

import classes.dadosDAO;
import classes.usuario;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author Kino
 */
public class cadNovaSenha extends javax.swing.JFrame {

    /**
     * Creates new form cadNovaSenha
     */
    URL iconURL = getClass().getResource("/img/HospitalFMU.png");
    ImageIcon icon = new ImageIcon(iconURL);
    public cadNovaSenha() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tituloLbl = new javax.swing.JLabel();
        novaSenhaLbl = new javax.swing.JLabel();
        confirmacaoLbl = new javax.swing.JLabel();
        novaSenhaField = new javax.swing.JPasswordField();
        confirmacaoField = new javax.swing.JPasswordField();
        senhasIguaisLbl = new javax.swing.JLabel();
        jLabelCapsLock = new javax.swing.JLabel();
        mostrarSenhaCheckBox = new javax.swing.JCheckBox();
        atualizarSenhaBtn = new javax.swing.JButton();
        usuarioLbl = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(icon.getImage());

        tituloLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ficha.png"))); // NOI18N
        tituloLbl.setText("Atualização de senha");

        novaSenhaLbl.setText("Nova senha:");

        confirmacaoLbl.setText("Confirmação:");

        novaSenhaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                novaSenhaFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                novaSenhaFieldKeyReleased(evt);
            }
        });

        confirmacaoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmacaoFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmacaoFieldKeyReleased(evt);
            }
        });

        senhasIguaisLbl.setText(" ");

        jLabelCapsLock.setForeground(new java.awt.Color(204, 0, 0));

        mostrarSenhaCheckBox.setText("Mostrar senha");
        mostrarSenhaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaCheckBoxActionPerformed(evt);
            }
        });

        atualizarSenhaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        atualizarSenhaBtn.setText("Atualizar senha");
        atualizarSenhaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarSenhaBtnActionPerformed(evt);
            }
        });

        usuarioLbl.setText("Usuário:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(novaSenhaLbl)
                            .addComponent(confirmacaoLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(mostrarSenhaCheckBox))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(atualizarSenhaBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(novaSenhaField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(confirmacaoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(usuarioLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(userLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(tituloLbl, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCapsLock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(senhasIguaisLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLbl)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuarioLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(novaSenhaLbl)
                        .addComponent(novaSenhaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCapsLock, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmacaoLbl)
                    .addComponent(confirmacaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhasIguaisLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarSenhaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarSenhaBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarSenhaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaCheckBoxActionPerformed
        // TODO add your handling code here:
        if (mostrarSenhaCheckBox.isSelected()){
            novaSenhaField.setEchoChar((char)0);
            confirmacaoField.setEchoChar((char)0);
        } else {
            novaSenhaField.setEchoChar('•');
            confirmacaoField.setEchoChar('•');
        }
    }//GEN-LAST:event_mostrarSenhaCheckBoxActionPerformed

    private void novaSenhaFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_novaSenhaFieldKeyPressed
        // TODO add your handling code here:
        if(enterKey(evt)){
            atualizarSenhaBtn.doClick();
        }
        boolean capsLock = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if (capsLock){
            jLabelCapsLock.setText("CAPS LOCK ATIVADO!");
        } else {
            jLabelCapsLock.setText("");
        }
    }//GEN-LAST:event_novaSenhaFieldKeyPressed

    private void novaSenhaFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_novaSenhaFieldKeyReleased
        // TODO add your handling code here:
        boolean capsLock = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if (capsLock){
            jLabelCapsLock.setText("CAPS LOCK ATIVADO!");
        } else {
            jLabelCapsLock.setText("");
        }
    }//GEN-LAST:event_novaSenhaFieldKeyReleased

    private void confirmacaoFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmacaoFieldKeyPressed
        // TODO add your handling code here:
        if(enterKey(evt)){
            atualizarSenhaBtn.doClick();
        }
        boolean capsLock = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if (capsLock){
            jLabelCapsLock.setText("CAPS LOCK ATIVADO!");
        } else {
            jLabelCapsLock.setText("");
        }
    }//GEN-LAST:event_confirmacaoFieldKeyPressed

    private void confirmacaoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmacaoFieldKeyReleased
        // TODO add your handling code here:
        boolean capsLock = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if (capsLock){
            jLabelCapsLock.setText("CAPS LOCK ATIVADO!");
        } else {
            jLabelCapsLock.setText("");
        }
        URL iconURL1 = getClass().getResource("/img/okay.png");
        URL iconURL2 = getClass().getResource("/img/sair.png");
        ImageIcon icon1 = new ImageIcon(iconURL1);
        ImageIcon icon2 = new ImageIcon(iconURL2);
        if (senhasIguais(novaSenhaField, confirmacaoField)){
            senhasIguaisLbl.setIcon(icon1);
        } else {
            senhasIguaisLbl.setIcon(icon2);
        }
    }//GEN-LAST:event_confirmacaoFieldKeyReleased

    private void atualizarSenhaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarSenhaBtnActionPerformed
        // TODO add your handling code here:
        if(atualizarSenha()){
            this.dispose();
        } else {
            novaSenhaField.setText("");
            confirmacaoField.setText("");
            senhasIguaisLbl.setIcon(null);
        }
    }//GEN-LAST:event_atualizarSenhaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadNovaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadNovaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadNovaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadNovaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadNovaSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarSenhaBtn;
    private javax.swing.JPasswordField confirmacaoField;
    private javax.swing.JLabel confirmacaoLbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCapsLock;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mostrarSenhaCheckBox;
    private javax.swing.JPasswordField novaSenhaField;
    private javax.swing.JLabel novaSenhaLbl;
    private javax.swing.JLabel senhasIguaisLbl;
    private javax.swing.JLabel tituloLbl;
    public static javax.swing.JLabel userLbl;
    private javax.swing.JLabel usuarioLbl;
    // End of variables declaration//GEN-END:variables

    private boolean atualizarSenha() {
        String senha = String.copyValueOf(novaSenhaField.getPassword());
        usuario user = new usuario();
        dadosDAO dados = new dadosDAO();
        user.setLogin(userLbl.getText());
        dados.readLogin(user);
        user.setSenha(senha);
        if (!senhasIguais(novaSenhaField, confirmacaoField)){
            JOptionPane.showMessageDialog(null, "Erro ao atualizar senha!\nPor favor, insira a mesma senha nos dois campos.", "Aviso", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (senha.length() < 6){
            JOptionPane.showMessageDialog(null, "Erro ao atualizar senha!\nPor favor, insira uma nova senha com pelo menos 6 caracteres.", "Aviso", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            if (dados.updateLogin(user)){
                JOptionPane.showMessageDialog(null, "Senha atualizada com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                return true;
            }
            return false;
        }
    }

    private boolean enterKey(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            return true;
        } else {
            return false;
        }
    }

    private boolean senhasIguais(JPasswordField novaSenhaField, JPasswordField confirmacaoField) {
        String p1 = String.copyValueOf(novaSenhaField.getPassword());
        String p2 = String.copyValueOf(confirmacaoField.getPassword());
        if (p1.equals(p2)){
            return true;
        } else {
            return false;
        }
    }
}
