/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualFormularios;

import classes.dadosDAO;
import classes.paciente;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kino
 */
public class cadPaciente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPaciente
     */
    URL iconURL = getClass().getResource("/img/HospitalFMU.png");
    ImageIcon icon = new ImageIcon(iconURL);
    public cadPaciente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBtnSexo = new javax.swing.ButtonGroup();
        tituloLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        dtNascimentoLabel = new javax.swing.JLabel();
        sexoLabel = new javax.swing.JLabel();
        femininoBtn = new javax.swing.JRadioButton();
        masculinoBtn = new javax.swing.JRadioButton();
        outrosBtn = new javax.swing.JRadioButton();
        telFixLabel = new javax.swing.JLabel();
        telCelLabel = new javax.swing.JLabel();
        cepLabel = new javax.swing.JLabel();
        concluirBtn = new javax.swing.JButton();
        nomeField = new javax.swing.JTextField();
        cpfField = new javax.swing.JFormattedTextField();
        dtNascField = new javax.swing.JFormattedTextField();
        telFixField = new javax.swing.JFormattedTextField();
        telCelField = new javax.swing.JFormattedTextField();
        cepField = new javax.swing.JFormattedTextField();
        planoSaudeLabel = new javax.swing.JLabel();
        planoSaudeCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(icon.getImage());

        tituloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ficha.png"))); // NOI18N
        tituloLabel.setText("Ficha de cadastro do paciente");

        nomeLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        nomeLabel.setText("Nome:");

        cpfLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        cpfLabel.setText("CPF:");

        dtNascimentoLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        dtNascimentoLabel.setText("Data de nascimento:");

        sexoLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        sexoLabel.setText("Sexo:");

        grupoBtnSexo.add(femininoBtn);
        femininoBtn.setText("Feminino");

        grupoBtnSexo.add(masculinoBtn);
        masculinoBtn.setText("Masculino");

        grupoBtnSexo.add(outrosBtn);
        outrosBtn.setText("Outros");

        telFixLabel.setText("Telefone fixo:");

        telCelLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        telCelLabel.setText("Telefone celular:");

        cepLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        cepLabel.setText("CEP:");

        concluirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/concluir.png"))); // NOI18N
        concluirBtn.setText("Concluir");
        concluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirBtnActionPerformed(evt);
            }
        });

        try {
            cpfField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            dtNascField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            telFixField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            telCelField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cepField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        planoSaudeLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        planoSaudeLabel.setText("Plano de saúde:");

        planoSaudeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allianz", "Amil", "Porto Seguro", "SulAmérica", "Unimed", "Não possui" }));
        planoSaudeCombo.setSelectedIndex(5);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setText("Campos em itálico são obrigatórios!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(concluirBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sexoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(femininoBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masculinoBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outrosBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(cpfLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpfField))
                                    .addComponent(dtNascimentoLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtNascField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(cepLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cepField))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(telCelLabel)
                                        .addComponent(telFixLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(telFixField)
                                    .addComponent(telCelField, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(planoSaudeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(planoSaudeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtNascimentoLabel)
                    .addComponent(dtNascField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoLabel)
                    .addComponent(femininoBtn)
                    .addComponent(masculinoBtn)
                    .addComponent(outrosBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telFixLabel)
                    .addComponent(telFixField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telCelLabel)
                    .addComponent(telCelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepLabel)
                    .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planoSaudeLabel)
                    .addComponent(planoSaudeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(concluirBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void concluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirBtnActionPerformed
        // TODO add your handling code here:
        if (cadastrarPac()) {
            this.dispose();
        }
        
    }//GEN-LAST:event_concluirBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cepField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JButton concluirBtn;
    private javax.swing.JFormattedTextField cpfField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JFormattedTextField dtNascField;
    private javax.swing.JLabel dtNascimentoLabel;
    private javax.swing.JRadioButton femininoBtn;
    private javax.swing.ButtonGroup grupoBtnSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton masculinoBtn;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JRadioButton outrosBtn;
    private javax.swing.JComboBox<String> planoSaudeCombo;
    private javax.swing.JLabel planoSaudeLabel;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JFormattedTextField telCelField;
    private javax.swing.JLabel telCelLabel;
    private javax.swing.JFormattedTextField telFixField;
    private javax.swing.JLabel telFixLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables

    private boolean cadastrarPac() {
        paciente pac = new paciente();
        dadosDAO dados = new dadosDAO();
        boolean sucesso = false;
        
        getFieldIntoObj(pac);
        if (!checkFields(pac)){
            if (dados.createPaciente(pac)){
                sucesso = true;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Campos obrigatórios em branco!\nPor favor, preencha corretamente.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        return sucesso;
    }

    private void getFieldIntoObj(paciente pac) {
        pac.setNome(nomeField.getText().toUpperCase());
        pac.setCpf(cpfField.getText().replaceAll("[.|\\-]", ""));
        pac.setDt_nascimento(dtNascField.getText());
        if (femininoBtn.isSelected()){
            pac.setSexo(femininoBtn.getText());
        } else if (masculinoBtn.isSelected()) {
            pac.setSexo(masculinoBtn.getText());
        } else if (outrosBtn.isSelected()) {
            pac.setSexo(outrosBtn.getText());
        }
        pac.setTelfix(telFixField.getText().replaceAll("[\\(|\\)|\\-\\s]", ""));
        pac.setTelcel(telCelField.getText().replaceAll("[\\(|\\)|\\-\\s]", ""));
        pac.setCep(cepField.getText().replaceAll("\\-", ""));
        pac.setPlano_saude((String) planoSaudeCombo.getSelectedItem());
    }

    private boolean checkFields(paciente pac) {
        boolean empty = true;
        try {
            if (pac.getNome().equals("") || pac.getCpf().equals("") || pac.getDt_nascimento().equals("") || 
                    pac.getSexo().equals("") || pac.getTelcel().equals("") || pac.getCep().equals("")){
                empty = true;
            } else {
                empty = false;
            }    
        } catch (NullPointerException ex) {
            System.out.println("Erro: " + ex);
        } finally {
            return empty;
        }
    }
}
