/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualMenus;

import javax.swing.JOptionPane;
import classes.dadosDAO;
import classes.funcionario;
import classes.usuario;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.net.URL;
import javax.swing.ImageIcon;
import visualFormularios.cadNovaSenha;



/**
 *
 * @author Kino
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form usuario
     */
    URL iconURL = getClass().getResource("/img/HospitalFMU.png");
    ImageIcon icon = new ImageIcon(iconURL);
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        userField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        PasswordLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        hospitalLabel = new javax.swing.JLabel();
        fmuLabel = new javax.swing.JLabel();
        mostrarSenha = new javax.swing.JCheckBox();
        jLabelCapsLock = new javax.swing.JLabel();
        fundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital FMU");
        setIconImage(icon.getImage());
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userField.setBackground(new java.awt.Color(255, 255, 255));
        userField.setForeground(new java.awt.Color(0, 0, 0));
        userField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userFieldKeyPressed(evt);
            }
        });
        jPanel2.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 133, -1));

        PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        PasswordField.setForeground(new java.awt.Color(0, 0, 0));
        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyReleased(evt);
            }
        });
        jPanel2.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 133, 26));

        loginButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.color2"));
        loginButton.setForeground(new java.awt.Color(0, 0, 0));
        loginButton.setText("Entrar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, 100, 70));

        PasswordLabel.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setText("Senha");
        jPanel2.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        userLabel.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 0, 0));
        userLabel.setText("Usuário");
        jPanel2.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, -1, -1));

        hospitalLabel.setFont(new java.awt.Font("Courier New", 1, 100)); // NOI18N
        hospitalLabel.setForeground(new java.awt.Color(0, 0, 0));
        hospitalLabel.setText("Hospital");
        jPanel2.add(hospitalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        fmuLabel.setFont(new java.awt.Font("Courier New", 1, 120)); // NOI18N
        fmuLabel.setForeground(new java.awt.Color(0, 0, 0));
        fmuLabel.setText("FMU");
        jPanel2.add(fmuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        mostrarSenha.setForeground(new java.awt.Color(0, 0, 0));
        mostrarSenha.setText("Mostrar senha");
        mostrarSenha.setContentAreaFilled(false);
        mostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaActionPerformed(evt);
            }
        });
        jPanel2.add(mostrarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, -1, -1));

        jLabelCapsLock.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(jLabelCapsLock, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 220, 30));

        fundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FundoLogin.jpg"))); // NOI18N
        jPanel2.add(fundoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        if (login()){
            String password = String.copyValueOf(PasswordField.getPassword());
            if (password.equals("fmu.123")){
                cadNovaSenha cadSenha = new cadNovaSenha();
                cadSenha.setVisible(true);
                cadSenha.userLbl.setText(userField.getText());
            } else {
                try {
                    this.dispose();
                    menu main = new menu();
                    usuario user = new usuario();
                    funcionario func = new funcionario();
                    user.setLogin(userField.getText());
                    func = pegarDadosLogin(user);
                    main.nomeLbl.setText(nomeProprio(func.getNome()));
                    main.cpfLbl.setText(formatarCpf(func.getCpf()));
                    main.cargoLbl.setText(func.getCargo());
                    main.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Dados inválidos!\nPor favor, tente novamente.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
        // TODO add your handling code here:
        if(enterKey(evt)){
            loginButton.doClick();
        }
        boolean capsLock = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if (capsLock){
            jLabelCapsLock.setText("CAPS LOCK ATIVADO!");
        } else {
            jLabelCapsLock.setText("");
        }
    }//GEN-LAST:event_PasswordFieldKeyPressed

    private void PasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyReleased
        // TODO add your handling code here:
        boolean capsLock = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if (capsLock){
            jLabelCapsLock.setText("CAPS LOCK ATIVADO!");
        } else {
            jLabelCapsLock.setText("");
        }
    }//GEN-LAST:event_PasswordFieldKeyReleased

    private void mostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaActionPerformed
        // TODO add your handling code here:
        if (mostrarSenha.isSelected()){
            PasswordField.setEchoChar((char)0);
        } else {
            PasswordField.setEchoChar('•');
        }
        
    }//GEN-LAST:event_mostrarSenhaActionPerformed

    private void userFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userFieldKeyPressed
        // TODO add your handling code here:
        if(enterKey(evt)){
            loginButton.doClick();
        }
    }//GEN-LAST:event_userFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel fmuLabel;
    private javax.swing.JLabel fundoLogin;
    private javax.swing.JLabel hospitalLabel;
    private javax.swing.JLabel jLabelCapsLock;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JCheckBox mostrarSenha;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables

    private boolean login() {
        usuario login = new usuario();
        dadosDAO dao = new dadosDAO();
        login.setLogin(userField.getText());
        login.setSenha(String.valueOf(PasswordField.getPassword()));
        if(dao.checkLogin(login) != null){
            return true;
        } else {
            return false;
        }
    }

    private boolean enterKey(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            return true;
        } else {
            return false;
        }
    }

    private funcionario pegarDadosLogin(usuario user) throws SQLException {
        dadosDAO dados = new dadosDAO();
        funcionario func = new funcionario();
        
        dados.readLogin(user);
        func.setId_func(user.getId_user());
        dados.searchFuncionarioByID(func);
        return func;
    }
    
    private String formatarCpf(String text) { // 44072588881
        String cpfFormatado = text.substring(0, 3) + "." + text.substring(3, 6) + "." + text.substring(6, 9) + "-" + text.substring(9);
        return cpfFormatado;
    }
    
    public String nomeProprio(String nome){
        char[] letras = nome.toLowerCase().toCharArray();
        boolean inicial = true;
        for (int i = 0; i < letras.length; i++){
            if (inicial && Character.isLetter(letras[i])){
                letras[i] = Character.toUpperCase(letras[i]);
                inicial = false;
            } else if (Character.isWhitespace(letras[i])) {
                inicial = true;
            }
        }
        return String.valueOf(letras);
    }
}
